### PR TITLE
Development

### PR DESCRIPTION
**Pull request by carienmol**
- New methods (save_nonzero, edge_detection, get_coordmedian) + tests
- Fixed a bug (frameheight/framewidth) + test
- Some cleanup and docstring improvements

### CODE REVIEW

**Comment by LaurensHomsFugro** [comment]
`/.github/workflows/python_package.yml`
The python 3.6 build is failing because `ubuntu-latest` (22.04) does not (yet) have support for that version, suggested workaround is to force `ubuntu-20.04` (or remove 3.6 from the `python-version` matrix): see https://github.com/actions/setup-python/issues/544

**Comment by laurenshoms** [comment]
`/.github/workflows/python_package.yml`
The python 3.6 build is failing because `ubuntu-latest` (22.04) does not (yet) have support for that version, suggested workaround is to force `ubuntu-20.04` (or remove `3.6` from the `python-version` matrix): see https://github.com/actions/setup-python/issues/544

**Comment by NickleDave** [comment]
No one asked me but you probably want to set "requires_python > 3.8" to follow SPEC 0000: https://scientific-python.org/specs/spec-0000/
unless you have some other dependencies that absolutely require Python 3.6, that don't jump out at me in your requirements.txt

**Comment by gbeckers** [comment]
> No one asked me but you probably want to set "requires_python > 3.8" to follow SPEC 0000: https://scientific-python.org/specs/spec-0000/ unless you have some other dependencies that absolutely require Python 3.6, that don't jump out at me in your requirements.txt

Many thanks Dave for the link! That is very useful info. We should ditch 3.6.

**Comment by gbeckers** [comment]
> `/.github/workflows/python_package.yml` The python 3.6 build is failing because `ubuntu-latest` (22.04) does not (yet) have support for that version, suggested workaround is to force `ubuntu-20.04` (or remove `3.6` from the `python-version` matrix): see [actions/setup-python#544](https://github.com/actions/setup-python/issues/544)

Thanks Laurens! Saw this too late but we solved it indeed by removing older Python. I see Github now also supports windows and mac testing so we included that.

**Pull request merged**
